/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const KeyFigure = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
export const HistoricalEvent = IDL.Record({
  'id' : IDL.Text,
  'region' : IDL.Text,
  'latitude' : IDL.Float64,
  'title' : IDL.Text,
  'year' : IDL.Int,
  'exactDate' : IDL.Opt(IDL.Text),
  'shortSummary' : IDL.Text,
  'civilization' : IDL.Text,
  'keyFigures' : IDL.Vec(KeyFigure),
  'longitude' : IDL.Float64,
  'category' : IDL.Text,
  'sources' : IDL.Vec(IDL.Text),
  'causes' : IDL.Vec(IDL.Text),
  'relatedEventIds' : IDL.Vec(IDL.Text),
  'fullDescription' : IDL.Text,
  'locationName' : IDL.Text,
  'consequences' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  'addEvent' : IDL.Func([HistoricalEvent], [IDL.Text], []),
  'getAllYears' : IDL.Func([], [IDL.Vec(IDL.Int)], ['query']),
  'getEventById' : IDL.Func([IDL.Text], [IDL.Opt(HistoricalEvent)], ['query']),
  'getEventsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(HistoricalEvent)],
      ['query'],
    ),
  'getEventsByRegion' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(HistoricalEvent)],
      ['query'],
    ),
  'getEventsByYear' : IDL.Func(
      [IDL.Int],
      [IDL.Vec(HistoricalEvent)],
      ['query'],
    ),
  'getEventsByYearRange' : IDL.Func(
      [IDL.Int, IDL.Int],
      [IDL.Vec(HistoricalEvent)],
      ['query'],
    ),
  'getRelatedEvents' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(HistoricalEvent)],
      ['query'],
    ),
  'getYearByRegion' : IDL.Func(
      [IDL.Int],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(HistoricalEvent)))],
      ['query'],
    ),
  'searchEvents' : IDL.Func([IDL.Text], [IDL.Vec(HistoricalEvent)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const KeyFigure = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  const HistoricalEvent = IDL.Record({
    'id' : IDL.Text,
    'region' : IDL.Text,
    'latitude' : IDL.Float64,
    'title' : IDL.Text,
    'year' : IDL.Int,
    'exactDate' : IDL.Opt(IDL.Text),
    'shortSummary' : IDL.Text,
    'civilization' : IDL.Text,
    'keyFigures' : IDL.Vec(KeyFigure),
    'longitude' : IDL.Float64,
    'category' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
    'causes' : IDL.Vec(IDL.Text),
    'relatedEventIds' : IDL.Vec(IDL.Text),
    'fullDescription' : IDL.Text,
    'locationName' : IDL.Text,
    'consequences' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    'addEvent' : IDL.Func([HistoricalEvent], [IDL.Text], []),
    'getAllYears' : IDL.Func([], [IDL.Vec(IDL.Int)], ['query']),
    'getEventById' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(HistoricalEvent)],
        ['query'],
      ),
    'getEventsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(HistoricalEvent)],
        ['query'],
      ),
    'getEventsByRegion' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(HistoricalEvent)],
        ['query'],
      ),
    'getEventsByYear' : IDL.Func(
        [IDL.Int],
        [IDL.Vec(HistoricalEvent)],
        ['query'],
      ),
    'getEventsByYearRange' : IDL.Func(
        [IDL.Int, IDL.Int],
        [IDL.Vec(HistoricalEvent)],
        ['query'],
      ),
    'getRelatedEvents' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(HistoricalEvent)],
        ['query'],
      ),
    'getYearByRegion' : IDL.Func(
        [IDL.Int],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(HistoricalEvent)))],
        ['query'],
      ),
    'searchEvents' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(HistoricalEvent)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };