/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface HistoricalEvent {
  'id' : string,
  'region' : string,
  'latitude' : number,
  'title' : string,
  'year' : bigint,
  'exactDate' : [] | [string],
  'shortSummary' : string,
  'civilization' : string,
  'keyFigures' : Array<KeyFigure>,
  'longitude' : number,
  'category' : string,
  'sources' : Array<string>,
  'causes' : Array<string>,
  'relatedEventIds' : Array<string>,
  'fullDescription' : string,
  'locationName' : string,
  'consequences' : Array<string>,
}
export interface KeyFigure { 'name' : string, 'role' : string }
export interface _SERVICE {
  'addEvent' : ActorMethod<[HistoricalEvent], string>,
  'getAllYears' : ActorMethod<[], Array<bigint>>,
  'getEventById' : ActorMethod<[string], [] | [HistoricalEvent]>,
  'getEventsByCategory' : ActorMethod<[string], Array<HistoricalEvent>>,
  'getEventsByRegion' : ActorMethod<[string], Array<HistoricalEvent>>,
  'getEventsByYear' : ActorMethod<[bigint], Array<HistoricalEvent>>,
  'getEventsByYearRange' : ActorMethod<
    [bigint, bigint],
    Array<HistoricalEvent>
  >,
  'getRelatedEvents' : ActorMethod<[string], Array<HistoricalEvent>>,
  'getYearByRegion' : ActorMethod<
    [bigint],
    Array<[string, Array<HistoricalEvent>]>
  >,
  'searchEvents' : ActorMethod<[string], Array<HistoricalEvent>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];