/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface HistoricalEvent {
    id: string;
    region: string;
    latitude: number;
    title: string;
    year: bigint;
    exactDate?: string;
    shortSummary: string;
    civilization: string;
    keyFigures: Array<KeyFigure>;
    longitude: number;
    category: string;
    sources: Array<string>;
    causes: Array<string>;
    relatedEventIds: Array<string>;
    fullDescription: string;
    locationName: string;
    consequences: Array<string>;
}
export interface KeyFigure {
    name: string;
    role: string;
}
export interface backendInterface {
    addEvent(event: HistoricalEvent): Promise<string>;
    getAllYears(): Promise<Array<bigint>>;
    getEventById(id: string): Promise<HistoricalEvent | null>;
    getEventsByCategory(category: string): Promise<Array<HistoricalEvent>>;
    getEventsByRegion(region: string): Promise<Array<HistoricalEvent>>;
    getEventsByYear(year: bigint): Promise<Array<HistoricalEvent>>;
    getEventsByYearRange(startYear: bigint, endYear: bigint): Promise<Array<HistoricalEvent>>;
    getRelatedEvents(eventId: string): Promise<Array<HistoricalEvent>>;
    getYearByRegion(year: bigint): Promise<Array<[string, Array<HistoricalEvent>]>>;
    searchEvents(keyword: string): Promise<Array<HistoricalEvent>>;
}
import type { HistoricalEvent as _HistoricalEvent, KeyFigure as _KeyFigure } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addEvent(arg0: HistoricalEvent): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addEvent(to_candid_HistoricalEvent_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEvent(to_candid_HistoricalEvent_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getAllYears(): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllYears();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllYears();
            return result;
        }
    }
    async getEventById(arg0: string): Promise<HistoricalEvent | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEventById(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEventById(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEventsByCategory(arg0: string): Promise<Array<HistoricalEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEventsByCategory(arg0);
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEventsByCategory(arg0);
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEventsByRegion(arg0: string): Promise<Array<HistoricalEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEventsByRegion(arg0);
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEventsByRegion(arg0);
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEventsByYear(arg0: bigint): Promise<Array<HistoricalEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEventsByYear(arg0);
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEventsByYear(arg0);
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEventsByYearRange(arg0: bigint, arg1: bigint): Promise<Array<HistoricalEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEventsByYearRange(arg0, arg1);
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEventsByYearRange(arg0, arg1);
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRelatedEvents(arg0: string): Promise<Array<HistoricalEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRelatedEvents(arg0);
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRelatedEvents(arg0);
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getYearByRegion(arg0: bigint): Promise<Array<[string, Array<HistoricalEvent>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getYearByRegion(arg0);
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getYearByRegion(arg0);
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchEvents(arg0: string): Promise<Array<HistoricalEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchEvents(arg0);
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchEvents(arg0);
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_HistoricalEvent_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HistoricalEvent): HistoricalEvent {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_HistoricalEvent]): HistoricalEvent | null {
    return value.length === 0 ? null : from_candid_HistoricalEvent_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    region: string;
    latitude: number;
    title: string;
    year: bigint;
    exactDate: [] | [string];
    shortSummary: string;
    civilization: string;
    keyFigures: Array<_KeyFigure>;
    longitude: number;
    category: string;
    sources: Array<string>;
    causes: Array<string>;
    relatedEventIds: Array<string>;
    fullDescription: string;
    locationName: string;
    consequences: Array<string>;
}): {
    id: string;
    region: string;
    latitude: number;
    title: string;
    year: bigint;
    exactDate?: string;
    shortSummary: string;
    civilization: string;
    keyFigures: Array<KeyFigure>;
    longitude: number;
    category: string;
    sources: Array<string>;
    causes: Array<string>;
    relatedEventIds: Array<string>;
    fullDescription: string;
    locationName: string;
    consequences: Array<string>;
} {
    return {
        id: value.id,
        region: value.region,
        latitude: value.latitude,
        title: value.title,
        year: value.year,
        exactDate: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.exactDate)),
        shortSummary: value.shortSummary,
        civilization: value.civilization,
        keyFigures: value.keyFigures,
        longitude: value.longitude,
        category: value.category,
        sources: value.sources,
        causes: value.causes,
        relatedEventIds: value.relatedEventIds,
        fullDescription: value.fullDescription,
        locationName: value.locationName,
        consequences: value.consequences
    };
}
function from_candid_tuple_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, Array<_HistoricalEvent>]): [string, Array<HistoricalEvent>] {
    return [
        value[0],
        from_candid_vec_n7(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_HistoricalEvent>): Array<HistoricalEvent> {
    return value.map((x)=>from_candid_HistoricalEvent_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, Array<_HistoricalEvent>]>): Array<[string, Array<HistoricalEvent>]> {
    return value.map((x)=>from_candid_tuple_n9(_uploadFile, _downloadFile, x));
}
function to_candid_HistoricalEvent_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HistoricalEvent): _HistoricalEvent {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    region: string;
    latitude: number;
    title: string;
    year: bigint;
    exactDate?: string;
    shortSummary: string;
    civilization: string;
    keyFigures: Array<KeyFigure>;
    longitude: number;
    category: string;
    sources: Array<string>;
    causes: Array<string>;
    relatedEventIds: Array<string>;
    fullDescription: string;
    locationName: string;
    consequences: Array<string>;
}): {
    id: string;
    region: string;
    latitude: number;
    title: string;
    year: bigint;
    exactDate: [] | [string];
    shortSummary: string;
    civilization: string;
    keyFigures: Array<_KeyFigure>;
    longitude: number;
    category: string;
    sources: Array<string>;
    causes: Array<string>;
    relatedEventIds: Array<string>;
    fullDescription: string;
    locationName: string;
    consequences: Array<string>;
} {
    return {
        id: value.id,
        region: value.region,
        latitude: value.latitude,
        title: value.title,
        year: value.year,
        exactDate: value.exactDate ? candid_some(value.exactDate) : candid_none(),
        shortSummary: value.shortSummary,
        civilization: value.civilization,
        keyFigures: value.keyFigures,
        longitude: value.longitude,
        category: value.category,
        sources: value.sources,
        causes: value.causes,
        relatedEventIds: value.relatedEventIds,
        fullDescription: value.fullDescription,
        locationName: value.locationName,
        consequences: value.consequences
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
